# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('title_html', models.TextField(blank=True)),
                ('title_latex', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('page_start', models.CharField(blank=True, max_length=10)),
                ('page_end', models.CharField(blank=True, max_length=10)),
                ('article_number', models.CharField(blank=True, max_length=16)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('ris', models.TextField(blank=True, null=True)),
                ('citeproc_json', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
