# Generated by Django 2.2.10 on 2020-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0002_auto_20190924_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='title',
            field=models.TextField(blank=True, help_text='Best-effort UTF-8 encoded plaintext version of title. No HTML tags, markdown or LaTeX.'),
        ),
        migrations.AlterField(
            model_name='ref',
            name='title_html',
            field=models.TextField(blank=True, help_text="Valid HTML version of title. Don't wrap with &lt;p&gt; or other tags."),
        ),
        migrations.AlterField(
            model_name='ref',
            name='title_latex',
            field=models.TextField(blank=True, help_text="LaTeX version of title. Don't escape backslashes (\\) but do use valid LaTeX for accented and similar characers."),
        ),
        migrations.AlterField(
            model_name='ref',
            name='url',
            field=models.URLField(blank=True, help_text='If not provided, this will be automatically constructed as https://dx.doi.org/&lt;DOI&gt; if possible.'),
        ),
    ]
